sudo: false
language: java

jdk:
  - oraclejdk8

install:
  - wget http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar xfz apache-maven-3.3.9-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - mvn -v

script: mvn -B -T 2 clean install

after_success:
  - mvn clean test jacoco:report coveralls:report
  - curl https://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
  - export CODACY_PROJECT_TOKEN=e583bcfe2e9642b4afc8addd00ed1ae1
  - codacy-coverage-reporter -l Java -r coverage.xml
  - mvn versions:display-dependency-updates versions:display-plugin-updates versions:display-property-updates | grep 'INFO' | grep '>' | sort | uniq